#COMPILE_OPTS=-Wall -O3 -mlittle-endian -mthumb -mcpu=cortex-m4 -ffreestanding -nostdlib
#export COMPILE_OPTS 
#ARM_PATH=/media/ProgramData/ARM/GNU/Tools/bin/
#export ARM_PATH

#all: 
#	$(MAKE) -C STM32F4xx_StdPeriph_Driver

#clean:
#	$(MAKE) -C STM32F4xx_StdPeriph_Driver clean

#.PHONY: all clean
