/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 10/07/2022 22:46:57
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            37000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            16000000
#define MX_HSE_VALUE                            24000000
#define MX_MSI_VALUE                            2097000
#define MX_PLLCLKFreq_Value                     24000000
#define MX_SYSCLKFreq_VALUE                     2097000
#define MX_HCLKFreq_Value                       2097000
#define MX_FCLKCortexFreq_Value                 2097000
#define MX_AHBFreq_Value                        2097000
#define MX_APB1Freq_Value                       2097000
#define MX_APB2Freq_Value                       2097000
#define MX_ADCFreq_Value                        16000000
#define MX_LCDFreq_Value                        37000
#define MX_RTCFreq_Value                        37000
#define MX_RTCHSEDivFreq_Value                  12000000
#define MX_TimerFreq_Value                      2097000
#define MX_VCOOutputFreq_Value                  48000000
#define MX_WatchDogFreq_Value                   37000
#define MX_MCOPinFreq_Value                     2097000
#define MX_VCOInputFreq_Value                   16000000

/*-------------------------------- ADC        --------------------------------*/

#define MX_ADC                                  1

/* GPIO Configuration */

/* Pin PC1 */
#define MX_ADC_IN11_Pin                         PC1
#define MX_ADC_IN11_GPIOx                       GPIOC
#define MX_ADC_IN11_GPIO_PuPd                   GPIO_NOPULL
#define MX_ADC_IN11_GPIO_Pin                    GPIO_PIN_1
#define MX_ADC_IN11_GPIO_Mode                   GPIO_MODE_ANALOG

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

#endif  /* __MX_DEVICE_H */
